function Comp5() {

    return (
      <div className="Comp5">
            <h2>Comp5</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend tincidunt dui, ac posuere dolor venenatis eu. Vivamus quis scelerisque elit, in tincidunt arcu. Nulla facilisi. Vivamus euismod justo nec lectus ultricies, a consequat nulla venenatis. Suspendisse non lectus ut nisl commodo feugiat nec vel urna. Nullam fringilla tristique arcu, vel ultrices lorem suscipit a.</p>
      </div>
    );
  }
  
  export default Comp5;